# Generated by Django 5.1.2 on 2024-10-15 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('etat', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('prenom', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('la_date', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.client')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(blank=True, default=0, null=True)),
                ('la_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.article')),
                ('Commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Ordre_expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=100, null=True)),
                ('cite', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.client')),
                ('commande', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.commande')),
            ],
        ),
    ]
